### PR TITLE
Optimize visualization

### PR DESCRIPTION
**Pull request by EasyPiPi**

### CODE REVIEW

**Comment by ndukler** [comment]
Can we turn any of the chunks of plotting code into nice modular functions to bring down the cyclomatic complexity? Otherwise I can up the limit for the linter but it does hint that the code is getting pretty unreadable.

**Comment by ndukler** [comment]
I see you actually already updated the linter. I suppose it's not a priority for now but at some point it would be nice to try and modularize the plotting code.

**Comment by ndukler** [comment]
I suppose we could turn creating each group of tracks into a function since they seem kinda independent of each other (with a bit of information passed along)?

**Comment by EasyPiPi** [comment]
Yep, I wish to clean up the results first, and we can come back here later. Another small issue is when there is only a single transcript, the visualization is a bit different because I use a compromised way to plot it. Otherwise I cannot plot it with color for some reasones.

**Comment by EasyPiPi** [comment]
> I suppose we could turn creating each group of tracks into a function since they seem kinda independent of each other (with a bit of information passed along)?

Yep, that's a good idea.

**Pull request merged**
